run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - goconst
    - misspell
    - gosec
    - stylecheck
    - gocritic
    - unparam
  disable:
    - depguard  # Disable overly restrictive import rules

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 2
    min-occurrences: 3  # Increased to reduce noise
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam
  
  gosec:
    excludes:
      - G404  # Allow math/rand for games
      - G304  # Allow file access for application functionality
  
  staticcheck:
    checks: ["all"]
  
  stylecheck:
    checks: ["all", "-ST1000"]  # Allow missing package comments for small packages
  
  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude gosec warnings for acceptable use cases
    - linters: 
        - gosec
      text: "G404.*weak random number generator"
    - linters:
        - gosec  
      text: "G304.*file inclusion"
    
    # Allow TODO comments in development
    - linters:
        - godox
      text: "TODO"
  
  # Don't skip warning about exported functions/types missing comments
  exclude-use-default: false
  
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-line: true
  print-linter-name: true

issues:
  uniq-by-line: false
